output   = "appdb"
pkgname  = "appdb"
add-global-variants = true
wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "iot"
host   = "65.109.128.168"
port   = 31432
user   = "leicom"
pass   = "h2WGqWQ4"
schema = "signify"
sslmode = "disable"


[[types]]
[types.match]
type = "null.Int"
nullable = true

[types.replace]
type = "null.Int32"

[[types]]
[types.match]
type = "int"

[types.replace]
type = "int32"
